.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. litenet_qt test_litenet_qt
clean: FORCE
	$(MAKE) -C .. litenet_qt_clean test_litenet_qt_clean
check: FORCE
	$(MAKE) -C .. test_litenet_qt_check
litenet-qt litenet-qt.exe: FORCE
	 $(MAKE) -C .. litenet_qt
apk: FORCE
	$(MAKE) -C .. litenet_qt_apk
